baseURL = "http://mhyfritz.com/blog/"
languageCode = "en-us"
title = "mhyfritz coredump"
theme = "tale"
pygmentsCodeFences = true
pygmentsStyle = "tango"
canonifyurls = true
googleAnalytics = "UA-54163720-1"
[Author]
    name = "Markus Hsi-Yang Fritz"
[permalinks]
  posts = "/:year/:month/:day/:slug/"
